package com.establishment.api.domain.enumerate;

public enum Types {
    LABORATÓRIO_DE_SAÚDE_PÚBLICA(80),
    CENTRO_REGULAMENTAÇÃO_DE_ACESSO(81),
    OFICINA_ORTOPÉDICA(79), 
    CENTRAL_DE_NOTIFICACAO_CAPTACAO_E_DISTRIBUICAO_DE_ORGAOS_ESTADUAL(82),
    UNIDADE_DE_ATENCAO_EM_REGIME_RESIDENCIAL(78),
    POLO_ACADEMIA_DE_SAUDE(74),
    TELESSAUDE(75),
    SERVICO_DE_ATENCAO_DOMICILIAR_ISOLADO_HOME_CARE(77),
    CENTRAL_DE_REGULACAO_MEDICA_DAS_URGENCIAS(76),
    CENTRO_DE_ATENCAO_HEMOTERAPIA_E_OU_HEMATOLOGICA(69),
    CENTRO_DE_ATENCAO_PSICOSSOCIAL(70),
    CENTRO_DE_APOIO_A_SAUDE_DA_FAMILIA(71),
    UNIDADE_DE_ATENCAO_A_SAUDE_INDIGENA(72),
    POSTO_DE_SAUDE(1),
    CENTRO_DE_SAUDE_UNIDADE_BASICA(2),
    POLICLINICA(4),
    CONSULTORIO_ISOLADO(22),
    UNIDADE_MOVEL_TERRESTRE(40),
    UNIDADE_MOVEL_DE_NIVEL_PRE_HOSPITALAR_NA_AREA_DE_URGENCIA(42),
    UNIDADE_MOVEL_FLUVIAL(32),
    CLINICA_CENTRO_DE_ESPECIALIDADE(36),
    CENTRAL_DE_REGULACAO_DE_SERVICOS_DE_SAUDE(64),
    FARMACIA(43),
    UNIDADE_DE_APOIO_DIAGNOSE_E_TERAPIA_SADT_ISOLADO(39),
    CENTRO_PARTO_NORMAL_ISOLADO(61),
    HOSPITAL_DIA_ISOLADO(62),
    UNIDADE_MISTA(15),
    PRONTO_SOCORRO_GERAL(20),
    PRONTO_SOCORRO_ESPECIALIZADO(21),
    HOSPITAL_GERAL(5),
    HOSPITAL_ESPECIALIZADO(7),
    UNIDADE_DE_VIGILANCIA_EM_SAUDE(50),
    LABORATORIO_CENTRAL_DE_SAUDE_PUBLICA_LACEN(67),
    PRONTO_ATENDIMENTO(73),
    COOPERATIVA_OU_EMPRESA_DE_CESSAO_DE_TRABALHORES_NA_SAUDE(60),
    CENTRAL_DE_GESTAO_EM_SAUDE(68),
    POLO_DE_PREVENCAO_DE_DOENCAS_E_AGRAVOS_E_PROMOCAO_DA_SAUDE(83),
    CENTRAL_DE_ABASTECIMENTO(84),
    CENTRO_DE_IMUNIZACAO(85),
    DESCONHECIDO(0);

    private int codType;

    Types(int codType) {
        this.codType = codType;
    }

    public int getCodType() {
        return codType;
    }
}
