version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: establishment_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: establishment_bd
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - spring-boot-network

volumes:
  mariadb_data:

networks:
  spring-boot-network:
    driver: bridge